##### `.streamlit/secrets.toml`
##### Car Pool
##### Open-Source, hosted on https://github.com/DrBenjamin/Car_Pool
##### Please reach out to ben@benbox.org for any questions
#### Customization
[custom]
organisation = "Company Name"
organisation_abbreviation = "CN"
logo_image = "images/Logo_Header.png"
sidebar_image = "images/Logo.png"

# User management
[passwords]
car = "pool"

# MySQL configuration
[connections.sql]
type = "sql"
dialect = "mysql"
host = "172.19.0.2"
port = 3306
database = "carpool"
username = "car"
password = "pool"